openapi: 3.0.3

info:
  title: Product Service
  version: 1.0.0

tags:
  - name: Product

paths:
  /products:

    get:
      tags:
        - Product

      summary: Get all products
      operationId: getProducts

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'

    post:
      tags:
        - Product

      summary: Create product
      operationId: createProduct

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

components:

  schemas:

    ProductRequest:

      type: object

      required:
        - name
        - price

      properties:

        name:
          type: string

        description:
          type: string

        price:
          type: number

        stock:
          type: integer

    ProductResponse:

      type: object

      properties:

        id:
          type: integer
          format: int64

        name:
          type: string

        description:
          type: string

        price:
          type: number

        stock:
          type: integer